#!/bin/bash
echo "CCC Task Activity on $HOSTNAME";
echo "==========================";
'/Applications/Carbon Copy Cloner.app/Contents/MacOS/ccc' -h | /usr/bin/tail
#/usr/bin/awk '/exit_status/ { print $2, "  ", $7, "  ", $11, $12, $13, $14, $15, "\t", $10 }' '/Library/Application Support/com.bombich.ccc/pht_debug.log' | /usr/bin/tail -18 | /usr/bin/sort;
echo
exit 0;
