#!/bin/bash
echo "Uptime for $HOSTNAME";
echo "=================================================="

# cat /var/log/backup-uptime.log | sed 's/[0-2]\.[0-9][0-9]/<span class="number_low">&<\/span>/g' | sed 's/[3-4]\.[0-9][0-9]/<span class="number_medium">&<\/span>/g' | sed 's/\ [0-9]*\.[0-9][0-9]/<span class="number_high">&<\/span>/g'
/bin/cat /var/log/backup-uptime.log;

echo;

echo "Logins for $HOSTNAME";
echo "=================================================="
/usr/bin/last -5;
echo


exit 0;

