#!/bin/bash
echo "Uptime for $HOSTNAME";
echo "=================================================="

cat /var/log/backup-uptime.log | sed 's/[0-2]\.[0-9][0-9]/<span class="number_low">&<\/span>/g' | sed 's/[3-4]\.[0-9][0-9]/<span class="number_medium">&<\/span>/g' | sed 's/\ [0-9]*\.[0-9][0-9]/<span class="number_high">&<\/span>/g'

echo;

echo "Logins for $HOSTNAME";
echo "=================================================="
last -5
echo


exit 0;

