#!/bin/bash

OPTIONS="-az --stats --timeout=300 --delete-after --delete-excluded"
DESTINATION="home"

echo "Rsync Backup on $HOSTNAME"
echo "========================="
echo `/bin/date`
rsync $OPTIONS /etc $DESTINATION:"$HOSTNAME"
rsync $OPTIONS /var $DESTINATION:"$HOSTNAME" \
     --exclude="/var/cache/" \
     --exclude="/var/lib/amavis/.spamassassin/bayes*" \
     --exclude="/var/lib/amavis/.spamassassin/auto-whitelist" \
     --exclude="/var/lib/amavis/tmp" \
     --exclude="/var/lib/apt/" \
     --exclude="/var/lib/clamav/" \
     --exclude="/var/lib/cyrus/proc/" \
     --exclude="/var/lib/dpkg/info/" \
     --exclude="/var/lib/mysql/*/*.frm" \
     --exclude="/var/lib/mysql/*/*.MY[DI]" \
     --exclude="/var/lib/php5/" \
     --exclude="/var/lib/ucf/cache/" \
     --exclude="/var/lock/" \
     --exclude="/var/run/" \
     --exclude="/var/spool/postfix/" \
     --exclude="/var/tmp/" \
     --exclude="cache/"
echo `/bin/date`
echo
exit 0
