#!/bin/bash

## THIS SCRIPT IS ONLY SUITABLE FOR OS X Lion Server and early versions of OS X Server for Mountain Lion.
## SEE THE MAVERICKS VERSION for Mavericks and Yosemite
##
## Keep a rolling seven days of backups of the individual databases for the services in OS X Server that use PostgreSQL
##
## Profile Manager: devicemgr_v2m0
## Wiki: collab
## Calendar and Contacts: caldav
##
## Don't forget to device your backup directory.

backupdir='/Library/Server/Backups/PostgreSQL/';
day=`/bin/date +%u`;
mkdir -p $backupdir/$day;

echo "PostgreSQL Backup for $HOSTNAME";
echo "================================="
echo `/bin/date`;
for database in `/usr/bin/psql -U _postgres -lt | awk '{print $1}' | grep -vE '\||^$|template0'`;
	do
	printf "Exporting $database...";
	/usr/bin/pg_dump -U _postgres -c $database | gzip -c > $backupdir/$day/$database.sql.gz;
	/bin/chmod 600 $backupdir/$day/$database.sql.gz;	
	printf "done\n";
done
echo `/bin/date`;
echo;
exit 0;
