#!/bin/bash
backupdir='/Library/Server/Backups/PostgreSQL/';
server_root='/Applications/Server.app/Contents/ServerRoot';

day=`date +%u`;
mkdir -p $backupdir/$day;

echo "PostgreSQL Backup for $HOSTNAME";
echo "================================="
echo `date`;
$server_root/usr/bin/pg_dump -U _devicemgr -h /Library/Server/ProfileManager/Config/var/PostgreSQL/ -c devicemgr_v2m0 | gzip -c > "$backupdir/$day/devicemgr_v2m0.sql.gz";
$server_root/usr/bin/pg_dump -U _teamsserver -h /Library/Server/Wiki/PostgresSocket/ -c collab | gzip -c > "$backupdir/$day/collab.sql.gz";
$server_root/usr/bin/pg_dump -U caldav -h /var/run/caldavd/PostgresSocket/ -c caldav | gzip -c > "$backupdir/$day/caldav.sql.gz";
chmod 600 "$backupdir/$day/devicemgr_v2m0.sql.gz";
chmod 600 "$backupdir/$day/collab.sql.gz";
chmod 600 "$backupdir/$day/caldav.sql.gz";
#for database in `$server_root/usr/bin/psql -U _postgres -h "$psql_socket" -lt | awk '{print $1}' | grep -vE '\||^$|template|postgres'`;
#	do
#	printf "Exporting $database...";
#	$server_root/usr/bin/pg_dump -U _postgres -h "$psql_socket" -c $database | gzip -c > $backupdir/$day/$database.sql.gz;
#	/bin/chmod 600 $backupdir/$day/$database.sql.gz;	
#	printf "done\n";
#done
echo `date`;
echo;
exit 0;

