#!/bin/bash

LOGDIR=/var/log
LOG=backup-uptime.log
LINES=24

###################################

# add an uptime to the bottom of the log
echo "`date +%Y-%m-%d` `/usr/bin/uptime`" >> $LOGDIR/$LOG

# if there's more than 24 entries (lines), truncate to lower 24
# this method safeguards against log file getting out of control

# check how many lines are in the log file
if [ $[ `wc -l < $LOGDIR/$LOG | tr -d '[[:space:]]'` ] -gt $LINES ]; then

        echo "`tail -n $LINES $LOGDIR/$LOG`" > $LOGDIR/$LOG

fi

exit 0;

