#!/bin/bash
echo "CCC Task Activity on $HOSTNAME";
echo "==========================";
# /usr/bin/grep -r exit_status '/Library/Application Support/com.bombich.ccc/pht_debug.log' | tail
/usr/bin/awk '/exit_status/ { print $2, "  ", $7, "  ", $11, $12, $13, $14, $15, "\t", $10 }' '/Library/Application Support/com.bombich.ccc/pht_debug.log' | /usr/bin/tail -18 | /usr/bin/sort;
echo
exit 0;
