#!/bin/bash

/bin/cat /var/log/backup.log

# ## Add the scripts that you want to run on this server
# /usr/local/bin/backup-df
# /usr/local/bin/backup-postqueue
# /usr/local/bin/backup-backupd
# /usr/local/bin/backup-mysql
# /usr/local/bin/backup-rsync
#
# ## Add the output of any remote servers to this report
# ssh host '/usr/local/bin/backup-report'

exit 0;
