#!/bin/bash

echo "Listserver retry queue for $HOSTNAME";
echo "===================================="
echo
echo 'Inbound'
echo "-------"
/bin/ls -l /Library/Server/Mail/Data/listserver/messages/inbound/* | /usr/bin/grep -vE ".lock_file|^total|^$|.*:$"
echo
echo 'Hold'
echo "-------"
/bin/ls -l /Library/Server/Mail/Data/listserver/messages/hold/
echo
echo 'Retry'
echo "-------"
/bin/ls -l /Library/Server/Mail/Data/listserver/messages/retry/
echo
exit 0;
