#!/bin/bash
backupdir=/var/backups/mysql
#clientfile=/etc/mysql/myclient.cnf
clientfile=/etc/mysql/debian.cnf

echo "MySQL Backup on $HOSTNAME";
echo "======================";
day=`date +%u`
mkdir -p $backupdir/$day
for database in `echo "show databases" | mysql --defaults-file=$clientfile | grep -vE 'Database|information_schema'`;
	do
	echo -n "Exporting $database..."
	mysqldump --defaults-file=$clientfile -c $database | gzip -c  > $backupdir/$day/$database.sql.gz
#	if test -e "$backupdir/$day/$database.sql.gz"
#		then
#		echo -n "cleaning..."
#		rm $backupdir/$day/$database.sql.gz
#	fi
#	echo -n "compressing..."
#	gzip $backupdir/$day/$database.sql
	echo "done"
done
echo
