#!/bin/bash
## Keep a rolling seven days of backups of the individual databases for the services in OS X Server that use PostgreSQL
##
## Profile Manager: devicemgr_v2m0
## Wiki: collab
## Calendar and Contacts: caldav
##
## Don't forget to device your backup directory.

backupdir="/Library/Server/Backups/PostgreSQL";
server_root="/Applications/Server.app/Contents/ServerRoot";

day=`date +%u`;
mkdir -p "$backupdir/$day";

echo "PostgreSQL Backup for $HOSTNAME";
echo "================================="
echo `date`;

echo -n "Backing up devicemgr... "
$server_root/usr/bin/pg_dump -U _devicemgr -h /Library/Server/ProfileManager/Config/var/PostgreSQL/ -c devicemgr_v2m0 | gzip -c > "$backupdir/$day/devicemgr_v2m0.sql.gz";
echo "Done."

echo -n "Backing up caldav... "
$server_root/usr/bin/pg_dump -U caldav -h /var/run/caldavd/PostgresSocket/ -c caldav | gzip -c > "$backupdir/$day/caldav.sql.gz";
echo "Done."

echo -n "Backing up collab... "
$server_root/usr/bin/pg_dump -U _teamsserver -h /Library/Server/Wiki/PostgresSocket/ -c collab | gzip -c > "$backupdir/$day/collab.sql.gz";
echo "Done."

chmod -R 600 "$backupdir/$day";
/bin/ls -lh "$backupdir/$day";

echo `date`;
echo;
exit 0;
