#!/bin/bash

# archive mode; equals -rlptgoD (no -H,-A,-X)
OPTIONS="-aHz --stats --timeout=300 --delete-after --delete-excluded"
DESTINATION="ffo"

echo "Rsync Backup on $HOSTNAME"
echo "========================="
echo `/bin/date`

echo "Syncing etc…"
rsync $OPTIONS /etc $DESTINATION:"$HOSTNAME" \
    --exclude="/etc/shadow" \
    --exclude="/etc/gshadow"
echo

echo "Syncing home…"
rsync $OPTIONS /home $DESTINATION:"$HOSTNAME" \
    --exclude=".npm/_cacache/" \
    --exclude=".cache/" \
    --exclude=".vscode-server"
echo

if [ -d "/opt/git" ]; then
	echo "Syncing opt/git"
	rsync $OPTIONS /opt/git $DESTINATION:"$HOSTNAME/opt/" \
		--exclude="online.broken.git/"
	echo
fi

echo "Syncing usr/local…"
rsync $OPTIONS /usr/local $DESTINATION:"$HOSTNAME/usr/"
echo

echo "Syncing var…"
rsync $OPTIONS /var $DESTINATION:"$HOSTNAME" \
    --exclude="cache/" \
    --exclude=".git/objects/" \
    --exclude="/var/lib/amavis/.spamassassin/auto-whitelist" \
    --exclude="/var/lib/amavis/tmp" \
    --exclude="/var/lib/amazon/ssm/Vault/Store/" \
    --exclude="/var/lib/apt/" \
    --exclude="/var/lib/clamav/" \
    --exclude="/var/lib/cyrus/proc/" \
    --exclude="/var/lib/dpkg/info/" \
    --exclude="/var/lib/mysql/*/*.frm" \
    --exclude="/var/lib/mysql/*/*.MY[DI]" \
    --exclude="/var/lib/php5/" \
    --exclude="/var/lib/ucf/cache/" \
    --exclude="/var/lock/" \
    --exclude="/var/run/" \
    --exclude="/var/spool/postfix/" \
    --exclude="/var/tmp/" \
    --exclude="/var/www/demo.fireflyeducation.com.au/" \
    --exclude="/var/www/online.fireflyeducation.com.au/" \
    --exclude="/var/www/staging.fireflyeducation.com.au/"
echo

echo `/bin/date`
echo
exit 0
