#!/bin/bash
## Show any recent successful backups.
## Then show the oldest and newest snapshows on your backup drive.

backup_drive="Time Machine Backups";
machine_name="Tina";

echo "Time Machine for $HOSTNAME";
echo "============================================="
/usr/bin/grep 'Backup completed successfully' /var/log/system.log | /usr/bin/tail -5
echo "";
echo "Earlist and Latest Backups"
echo "============================================="
/bin/ls "/Volumes/$backup_drive/Backups.backupdb/$machine_name/" | /usr/bin/head -n 2
/bin/ls "/Volumes/$backup_drive/Backups.backupdb/$machine_name/" | /usr/bin/grep -v Latest | /usr/bin/tail -n 2
echo;
exit 0;
